Fix build: depend on mirage-types, not mirage
Error was:

    File "mirage/tftp_mirage.ml", line 23, characters 18-32:
    Error: Unbound module V1_LWT